# Generated by Django 6.0.5 on 2026-05-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_remove_delivery_tracking_number_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='estimated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('assigned', 'Назначена'), ('in_transit', 'В пути'), ('delivered', 'Доставлено'), ('cancelled', 'Отменено')], default='pending', max_length=20),
        ),
    ]
