# Generated by Django 6.0.5 on 2026-05-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_delivery_comment_delivery_delivered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='address',
            field=models.CharField(default='Unknown address', max_length=255),
        ),
    ]
