# Generated by Django 6.0.5 on 2026-05-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_delivery_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='status',
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('on_way', 'Выехал'), ('at_client', 'У клиента'), ('returned', 'Возврат'), ('completed', 'Завершён')], default='pending', max_length=30),
        ),
    ]
