# Generated by Django 6.0.5 on 2026-05-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_remove_delivery_status_delivery_delivery_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_address',
        ),
        migrations.AddField(
            model_name='delivery',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='delivery',
            name='route',
            field=models.TextField(blank=True),
        ),
    ]
