# Generated by Django 6.0.5 on 2026-05-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_remove_delivery_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Создана'), ('on_way', 'Выехал'), ('at_client', 'У клиента'), ('returned', 'Возврат'), ('completed', 'Завершён')], default='pending', max_length=30),
        ),
    ]
