# Generated by Django 6.0.5 on 2026-05-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_alter_delivery_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='route',
        ),
        migrations.AddField(
            model_name='delivery',
            name='end_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='delivery',
            name='route_duration_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='route_geometry',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='start_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
