# Generated by Django 6.0.5 on 2026-05-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_product_options_rename_name_product_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
