# Generated by Django 6.0.5 on 2026-05-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_product_reserved_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
