# Generated by Django 6.0.5 on 2026-05-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Заказчик'), ('supplier', 'Поставщик'), ('courier', 'Курьер'), ('manager', 'Менеджер'), ('admin', 'Администратор')], default='customer', max_length=20),
        ),
    ]
