# Generated by Django 6.0.5 on 2026-05-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdocument',
            name='cargo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shippingdocument',
            name='cargo_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shippingdocument',
            name='driver_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shippingdocument',
            name='number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='shippingdocument',
            name='places_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shippingdocument',
            name='recipient_company',
            field=models.CharField(default='Не указан', max_length=255),
        ),
        migrations.AddField(
            model_name='shippingdocument',
            name='sender_company',
            field=models.CharField(default='ООО "СИНХРА"', max_length=255),
        ),
        migrations.AddField(
            model_name='shippingdocument',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
