# Generated by Django 6.0.5 on 2026-05-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_approved_at_order_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтверждён'), ('assembly', 'В сборке'), ('shipping', 'Отгружен'), ('delivered', 'Доставлен'), ('closed', 'Закрыт'), ('cancelled', 'Отменён')], default='new', max_length=20),
        ),
    ]
