# Generated by Django 6.0.5 on 2026-05-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтверждён'), ('assembly', 'В сборке'), ('shipped', 'Отгружен'), ('delivering', 'Доставляется'), ('delivered', 'Доставлен'), ('closed', 'Закрыт'), ('cancelled', 'Отменён')], default='new', max_length=20),
        ),
    ]
